name: "🐛 Bug report"
description: "[fix] Zgłoś błąd w działającym systemie produkcyjnym"
type: "Bug"
body:
  - type: markdown
    attributes:
      value: |
        Zgłoś błąd w działającym systemie produkcyjnym
        
        > [!IMPORTANT]
        > Pamiętaj, że zgłoszenie błędu **dotyczy tylko instancji produkcyjnej**, a więc nie może pochodzić z developa!

        > [!TIP]
        > Potrzebujesz pomocy? Przewiń na sam dół - tam są podpowiedzi jak opisać zgłoszenie.
        
  - type: input
    id: instance
    attributes:
      label: 🌐 Instancja
      description: |
        Nazwa instancji widoczna jako subdomena w adresie URL przeglądarki
      placeholder: staging
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: 🧠 Opis problemu
      description: Opisz, co nie działa, gdzie występuje błąd i co dzieje się obecnie.
      placeholder: |
        Podczas zapisywania ustawień profilu użytkownika system zapisuje niepoprawną strefę czasową, co powoduje błędne wyświetlanie dat i godzin.

        System zapisuje inną strefę czasową (UTC), mimo poprawnego wyboru w formularzu.
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: 🔁 Kroki do odtworzenia
      description: Krok po kroku opisz, jak odtworzyć błąd.
      placeholder: |
        1. Zaloguj się jako użytkownik
        2. Przejdź do edycji profilu
        3. Ustaw strefę czasową „Europe/Warsaw”
        4. Zapisz zmiany
        5. Odśwież stronę
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: ✅ Kryteria akceptacji
      description: Jednoznaczne warunki, które muszą być spełnione, aby uznać fix za poprawnie ukończony.
      placeholder: |
        Wybrana strefa czasowa powinna zostać poprawnie zapisana i wyświetlana po ponownym załadowaniu profilu.
    validations:
      required: true
      
  - type: textarea
    id: notes
    attributes:
      label: 🧩 Dodatkowe informacje
      description: Wpisz dodatkowe informacje pozwalające na sprawniejszy proces naprawy
      placeholder: |
        - środowisko gdzie występuje problem -> Chrome 12
        - wpływ błędu na użytkowników lub system -> błędne daty w raportach
        - logi, screenshoty lub linki, jeśli dostępne -> screenshot błędnej strefy

  - type: markdown
    attributes:
      value: |
        **ℹ️ Jak skutecznie zgłosić błąd? – Szybkie wskazówki**
        
        **Sprawdź adres URL**  
        Upewnij się, że problem występuje na produkcji. W polu „Instancja” wpisz nazwę klienta lub subdomenę, na której widoczny jest błąd.

        **Bądź precyzyjny w krokach**  
        Opisz drogę do błędu tak, jakbyś prowadził kogoś za rękę. Każde kliknięcie ma znaczenie – programista musi umieć „zepsuć” system w ten sam sposób.

        **Oczekiwane vs. Rzeczywiste**  
        Jasno oddziel to, co się stało (np. „widzę biały ekran”), od tego, co powinno się stać (np. „powinien wyskoczyć komunikat o zapisie”).

        **Kontekst to klucz**  
        Napisz, czy problem dotyczy tylko jednej przeglądarki (np. Safari) lub konkretnego użytkownika. To drastycznie przyspiesza diagnozę.

        **Dołącz dowody**  
        Zrzut ekranu (nawet zrobiony telefonem) lub nagranie wideo często mówi więcej niż sto słów opisu.
